### ISSUE TITLE
Add login form

### ISSUE THREAD

**Issue by ALOKARYAN51** [ALOKARYAN51/E-Library-frontend#2]
- [x] Integrate login form.

**Comment by qwerty-rgb** [comment]
sir please assign me this i will do it :)

**Comment by anoyash** [comment]
Hello @ALOKARYAN51  can I do this ?

**Comment by qwerty-rgb** [comment]
i have done it making a pr request in10 mins

**Comment by ALOKARYAN51** [comment]
open for everyone  @qwerty-rgb @Ashutosh-web

**Comment by qwerty-rgb** [comment]
#7
