### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ALOKARYAN51** [ALOKARYAN51/E-Library-frontend#3]
- [ ] Fix navbar bug in mobile view.

**Comment by akshitkumar450** [comment]
i would like to contribute..please assign to me..as please elaborate the the problem in mobile view

**Comment by ALOKARYAN51** [comment]
ok @akshitkumar450 while clicking on navbar whole content dropdown along with dropdown menu. Inspect you will understand.

**Comment by ALOKARYAN51** [comment]
Issue is open for everyone

**Comment by rutujanemane** [comment]
I can work on it.

**Comment by ALOKARYAN51** [comment]
yes go ahead @rutujanemane

**Comment by rutujanemane** [comment]
I have made a PR.  @ALOKARYAN51 Kindly check if your issue is solved and suggest changes if any.

**Comment by rutujanemane** [comment]
@ALOKARYAN51 have you checked my PR? Is it fixing your specified issue?
