### ISSUE TITLE
Add dark/light mode button.

### ISSUE THREAD

**Issue by ALOKARYAN51** [ALOKARYAN51/E-Library-frontend#4]
Add button in Navbar
Adjust the theme button in navbar.
Check it mobile view as well.

**Comment by kratikasinghal** [comment]
Hi @ALOKARYAN51 Can i work on this?

**Comment by ALOKARYAN51** [comment]
Open to everyone. @kratikasinghal

**Comment by fajarsj** [comment]
Hi @ALOKARYAN51 i have a PR for this can you please kindly check it, 

here's the PR : https://github.com/ALOKARYAN51/E-Library-frontend/pull/6

**Comment by Abhishekchauhan089** [comment]
@ALOKARYAN51  I would like to work on this issue...can you please assign me

**Comment by ALOKARYAN51** [comment]
Okk go ahead just adjust the button in navbar and check it in mobile view as well .@Abhishekchauhan089 create PR In another branch check the readme steps.
