### ISSUE TITLE
Add light mode.

### ISSUE THREAD

**Issue by ALOKARYAN51** [ALOKARYAN51/E-Library-frontend#5]

**Comment by grvsood** [comment]
lemme do it

**Comment by grvsood** [comment]
#6 merge this.. it's prerequisite

**Comment by ALOKARYAN51** [comment]
#6 merged @grvsood

**Comment by chetas411** [comment]
@ALOKARYAN51 Can you review the PR?

**Comment by grvsood** [comment]
not good when i had already claimed this issue @chetas411

**Comment by chetas411** [comment]
> 
> 
> not good when i had already claimed this issue @chetas411

@ALOKARYAN51  but you have not been assigned and it was open for all i think .

**Comment by ALOKARYAN51** [comment]
Don't worry i will review all @grvsood @chetas411

**Comment by ALOKARYAN51** [comment]
Take you time then create pull request, i am happy that you all are working on my project  @grvsood

**Comment by chetas411** [comment]
> 
> 
> > not good when i had already claimed this issue @chetas411
> 
> Sorry but you have not been assigned and it was open for all i think .



> 
> 
> Don't worry i will review all @grvsood @chetas411

I created pull request for this #12 , waiting for you to review .
